module.exports = [
  'Nebula', 'Orion', 'Vega', 'Sirius', 'Altair', 'Rigel', 'Polaris', 'Castor', 'Pollux', 'Andromeda',
  'Galaxy', 'Cosmos', 'Stellar', 'Nova', 'Comet', 'Meteor', 'Asteroid', 'Quasar', 'Pulsar', 'Neutron',
  'Phoenix', 'Dragon', 'Falcon', 'Eagle', 'Hawk', 'Raven', 'Wolf', 'Tiger', 'Lion', 'Panther',
  'Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', 'Zeta', 'Eta', 'Theta', 'Iota', 'Kappa',
  'Cipher', 'Matrix', 'Vector', 'Pixel', 'Binary', 'Quantum', 'Photon', 'Electron', 'Proton', 'Neutron',
  'Titan', 'Atlas', 'Hermes', 'Apollo', 'Artemis', 'Athena', 'Zeus', 'Poseidon', 'Hades', 'Ares',
  'Crimson', 'Azure', 'Violet', 'Emerald', 'Golden', 'Silver', 'Platinum', 'Diamond', 'Ruby', 'Sapphire',
  'Storm', 'Thunder', 'Lightning', 'Blizzard', 'Tornado', 'Hurricane', 'Cyclone', 'Typhoon', 'Monsoon', 'Gale',
  'Shadow', 'Ghost', 'Phantom', 'Specter', 'Wraith', 'Spirit', 'Soul', 'Echo', 'Mirage', 'Illusion',
  'Blade', 'Sword', 'Spear', 'Arrow', 'Shield', 'Armor', 'Helmet', 'Gauntlet', 'Boot', 'Cloak',
  'Fire', 'Ice', 'Earth', 'Air', 'Water', 'Metal', 'Wood', 'Light', 'Dark', 'Void',
  'Hunter', 'Ranger', 'Scout', 'Warrior', 'Knight', 'Paladin', 'Rogue', 'Assassin', 'Mage', 'Wizard',
  'Ace', 'Chief', 'Major', 'Captain', 'Admiral', 'General', 'Marshal', 'Commander', 'Leader', 'Boss',
  'Cyber', 'Tech', 'Data', 'Code', 'Hack', 'Link', 'Node', 'Grid', 'Net', 'Web',
  'Star', 'Moon', 'Sun', 'Earth', 'Mars', 'Venus', 'Jupiter', 'Saturn', 'Uranus', 'Neptune',
  'Apex', 'Prime', 'Ultra', 'Super', 'Mega', 'Giga', 'Tera', 'Peta', 'Exa', 'Zetta',
  'Frost', 'Flame', 'Spark', 'Bolt', 'Charge', 'Surge', 'Pulse', 'Wave', 'Beam', 'Ray',
  'Viper', 'Cobra', 'Python', 'Boa', 'Mamba', 'Adder', 'Asp', 'Krait', 'Taipan', 'Coral',
  'Laser', 'Plasma', 'Fusion', 'Fission', 'Atomic', 'Nuclear', 'Particle', 'Molecule', 'Atom', 'Ion',
  'Turbo', 'Nitro', 'Boost', 'Rush', 'Speed', 'Swift', 'Flash', 'Dash', 'Zoom', 'Blur'
];
